const header=document.getElementById('site-header');window.addEventListener('scroll',()=>{header.classList.toggle('visible',window.scrollY>100)},{passive:true});
    const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;document.getElementById('hero-group')?.classList.add('in-view');
    const revealObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target)}})},{threshold:0.12,rootMargin:'0px 0px -8% 0px'});
    if(!prefersReducedMotion){document.querySelectorAll('.reveal, .reveal-group:not(#hero-group)').forEach(el=>revealObserver.observe(el))}else{document.querySelectorAll('.reveal, .reveal-group').forEach(el=>el.classList.add('in-view'))}
    const cardNotif=document.getElementById('card-notif');if(cardNotif&&!prefersReducedMotion){const notifItems=cardNotif.querySelectorAll('.notif-item');const notifObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){notifItems.forEach((item,i)=>{setTimeout(()=>item.classList.add('visible'),i*350)});notifObserver.unobserve(cardNotif)}},{threshold:0.3});notifObserver.observe(cardNotif)}else{document.querySelectorAll('.notif-item').forEach(el=>el.classList.add('visible'))}
    const cardAttend=document.getElementById('card-attend');if(cardAttend&&!prefersReducedMotion){let attendDone=false;const attendObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!attendDone){attendDone=true;const codeEl=document.getElementById('totp-attend');const badgeEl=document.getElementById('attend-badge');setTimeout(()=>{codeEl.textContent='482  917';codeEl.classList.add('revealed');setTimeout(()=>badgeEl.classList.add('show'),400)},800);attendObserver.unobserve(cardAttend)}},{threshold:0.4});attendObserver.observe(cardAttend)}else{const c=document.getElementById('totp-attend');if(c){c.textContent='482  917';c.classList.add('revealed')}document.getElementById('attend-badge')?.classList.add('show')}
    const cardVoice=document.getElementById('card-voice');if(cardVoice){const phrases={tamil:'"உடைந்த குழாய் புதியதாக மாற்றப்பட்டது"',malayalam:'"പൊട്ടിയ പൈപ്പ് പുതിയ ടാപ്പ് വച്ച് മാറ്റി"',kannada:'"ಮುರಿದ ಪೈಪ್ ತೆಗೆದು ಹೊಸ ಟ್ಯಾಪ್ ಹಾಕಿದ್ದೇವೆ"',telugu:'"పగిలిన పైపును కొత్త ట్యాప్‌తో మార్చాము"',marathi:'"तुटलेली पाईप नवीन टॅपने बदलली"',bangla:'"ভেঙে যাওয়া পাইপটি নতুন ট্যাপ দিয়ে পরিবর্তন করা হয়েছে"',hindi:'"टूटी हुई पाइप को नए टैप से बदल दिया गया है"',english:'"The broken pipe has been replaced with a new tap"'};
    const langOrder=['tamil','malayalam','kannada','telugu','marathi','bangla','hindi','english'];
    const tags=document.querySelectorAll('#voice-tags .voice-tag');const transcript=document.getElementById('voice-transcript');const waveform=document.getElementById('voice-waveform');
    let currentLangIndex=7;let autoCycleInterval;let userInteracted=false;
    function activateLang(lang){tags.forEach(t=>t.classList.remove('active'));const activeTag=document.querySelector(`[data-lang="${lang}"]`);if(activeTag)activeTag.classList.add('active');if(!prefersReducedMotion){const bars=waveform.querySelectorAll('.voice-bar');bars.forEach((bar,i)=>{bar.classList.add('active');bar.style.animation=`wave 0.9s ease-in-out infinite`;bar.style.animationDelay=`${i*0.08}s`;setTimeout(()=>{bar.classList.remove('active');bar.style.animation='none'},1500)})}const text=phrases[lang];transcript.textContent='';let i=0;const typeInterval=setInterval(()=>{if(i<text.length){transcript.textContent+=text[i];i++}else{clearInterval(typeInterval)}},25)}
    function cycleLanguages(){currentLangIndex=(currentLangIndex+1)%langOrder.length;activateLang(langOrder[currentLangIndex])}
    function startAutoCycle(){stopAutoCycle();autoCycleInterval=setInterval(cycleLanguages,3000)}
    function stopAutoCycle(){if(autoCycleInterval){clearInterval(autoCycleInterval);autoCycleInterval=null}}
    tags.forEach(tag=>{tag.addEventListener('click',()=>{userInteracted=true;stopAutoCycle();const lang=tag.dataset.lang;currentLangIndex=langOrder.indexOf(lang);activateLang(lang);setTimeout(()=>{userInteracted=false;startAutoCycle()},8000)})});
    if(!prefersReducedMotion){startAutoCycle()}}
    const cardComplete=document.getElementById('card-complete');if(cardComplete&&!prefersReducedMotion){let proofInterval;function animateProof(){const steps=['proof-1','proof-2','proof-3'];steps.forEach(id=>document.getElementById(id)?.classList.remove('proven'));steps.forEach((id,i)=>{setTimeout(()=>document.getElementById(id)?.classList.add('proven'),600+i*700)})}
    const proofObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){animateProof();proofInterval=setInterval(animateProof,4000)}else{clearInterval(proofInterval);const steps=['proof-1','proof-2','proof-3'];steps.forEach(id=>document.getElementById(id)?.classList.remove('proven'))}},{threshold:0.35});proofObserver.observe(cardComplete)}else{['proof-1','proof-2','proof-3'].forEach(id=>document.getElementById(id)?.classList.add('proven'))}
    const form=document.getElementById('demo-form');const formConfirm=document.getElementById('form-confirm');const formError=document.getElementById('form-error');function showError(msg){formError.textContent=msg;formError.style.display='block'}function clearError(){formError.textContent='';formError.style.display='none'}function isValidEmail(e){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}
    form.addEventListener('submit',async(e)=>{e.preventDefault();clearError();const salutation=form.salutation.value.trim();const name=form.name.value.trim();const institution=form.institution.value.trim();const phone=form.phone.value.trim();const email=form.email.value.trim();if(!name){showError('Please enter your name.');form.name.focus();return}if(!institution){showError('Please enter your institution.');form.institution.focus();return}if(!phone){showError('Please enter your phone number.');form.phone.focus();return}if(!email){showError('Please enter your email.');form.email.focus();return}if(!isValidEmail(email)){showError('Please enter a valid email address.');form.email.focus();return}try{const res=await fetch(form.action,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({salutation,name,institution,phone,email})});if(res.ok){form.style.display='none';formConfirm.style.display='block'}else{showError('Something went wrong. Please try again or email us directly.')}}catch{showError('Unable to submit. Please check your connection and try again.')}});
// Mobile menu toggle
const mobileToggle = document.querySelector('.mobile-toggle');
const headerNav = document.querySelector('.header-nav');
if(mobileToggle && headerNav) {
  mobileToggle.addEventListener('click', () => {
    headerNav.classList.toggle('active');
  });
}
const navLinks = document.querySelectorAll('.header-nav .nav-link');
navLinks.forEach(link => {
  link.addEventListener('click', () => {
    headerNav.classList.remove('active');
  });
});